# Generated by Django 3.2.6 on 2021-09-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ('name',), 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
